function [L U P] = LUcz(A);
    n = size(A, 1);
    U = zeros(n);
    L = eye(n);
    P = eye(n);
    for k = 1:n;
        [a ii] = max(A(k:end, k));
        ii = ii + k - 1;
        rr = A(k, :);
        A(k, :) = A(ii, :);
        A(ii, :) = rr;
        rp = P(k, :);
        P(k, :) = P(ii, :);
        P(ii, :) = rp;
        for l = (k+1):n;
            m = A(l, k) / A(k, k);
            L(l, k) = m;
            A(l, :) = A(l, :) - m .* A(k, :);
        end;
    end;
    U = A;
